#!/usr/bin/env bash
# Print "Best School" 10 times; on the 9th time, also print "Hi"
count=1
while [ $count -le 10 ]; do
  echo "Best School"
  if [ $count -eq 9 ]; then
    echo "Hi"
  fi
  ((count++))
done
