#!/usr/bin/env bash
# Loop from 1 to 20 and use a case statement to display superstitious messages
i=1
while [ $i -le 20 ]; do
  echo "$i"
  case $i in
    4)
      echo "bad luck from China"
      ;;
    9)
      echo "bad luck from Japan"
      ;;
    17)
      echo "bad luck from Italy"
      ;;
  esac
  ((i++))
done
